version: 2
jobs:
  build:
    working_directory: /work
    docker:
      - image: lrks/desk:kancolle
    steps:
      - checkout
      - run: build.rb --pdf4print --pdf4publish --epub --workdir=/work/src --margin=3mm --verbose
      - store_artifacts:
          path: /work/src/working_temporary_directory/original.pdf
      - store_artifacts:
          path: /work/src/working_temporary_directory/honbun.pdf
      - store_artifacts:
          path: /work/src/working_temporary_directory/publish-raw.pdf
      - store_artifacts:
          path: /work/src/working_temporary_directory/publish-ebook.pdf
      - store_artifacts:
          path: /work/src/working_temporary_directory/publish.epub
      - store_artifacts:
          path: /work/src/working_temporary_directory/book-text
